### ISSUE TITLE
Support multiple configuration files

### ISSUE THREAD

**Issue by krlmlr** [KentonWhite/ProjectTemplate#88]
- [ ] New parameter to `load.project` and `reload.project`, interpreted as basename without extension in the `config` directory
- [ ] Cascading configuration

Closes #82.

**Comment by connectedblue** [comment]
Does #152 address the requirement?

The PR will read a `custom.dcf` file if it exists in the config directory.  This contains config that is specific to a particular project, e.g. it might be important to cache some derived dataframes.  This could be specified in `custom.dcf` as follows:
`cache_obj:  foo, bar`
and then a processing line in a munge script could call:
`lapply(strsplit(config$cache_objs, '\\s*,\\s*')[[1]], cache)`
to cache whatever objects are in cache_obj.  This makes it easier to maintain the munge script if you have a large number of objects to cache.

**Comment by KentonWhite** [comment]
I've dug into what `custom.dcf` does and I agree it doesn't really address the wish here. I'll put my thoughts on `custom.dcf` in PR #152.

**Comment by Hugovdberg** [comment]
I agree with @KentonWhite that this `custom.dcf` does not provide the functionality requested. This issue calls for a call like `load.project(override_config = list(), config = 'global.dcf')`, so you can on the fly determine which config to use. So instead of your method to use `custom.dcf` if it exists, you can choose which to me seems a better way to go about this.
